CREATE TABLE IF NOT EXISTS `#__virtuemart_payment_plg_alliance_order` (
    `entity_id` INT AUTO_INCREMENT NOT NULL,
    `order_id` INT NOT NULL,
    `merchant_request_id` VARCHAR(255) NOT NULL,
    `hpp_order_id` VARCHAR(255) NOT NULL,
    `merchant_id` VARCHAR(255) NOT NULL,
    `coin_amount` INT NOT NULL,
    `hpp_pay_type` VARCHAR(50) NOT NULL,
    `order_status` VARCHAR(50) NOT NULL,
    `payment_methods` LONGTEXT NOT NULL,
    `create_date` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    `operation_id` VARCHAR(255) NOT NULL,
    `ecom_order_id` VARCHAR(255) NOT NULL,
    `is_callback_returned` TINYINT(1) NOT NULL DEFAULT 0,
    `callback_data` LONGTEXT NOT NULL,
    `expired_order_date` DATETIME NOT NULL,
    PRIMARY KEY (`entity_id`),
    INDEX `idx_alliance_order_id` (`order_id`),
    INDEX `idx_alliance_merchant_req_id` (`merchant_request_id`),
    INDEX `idx_alliance_hpp_order_id` (`hpp_order_id`),
    INDEX `idx_alliance_merchant_id` (`merchant_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__virtuemart_payment_plg_alliance_refund` (
    `refund_id` INT AUTO_INCREMENT NOT NULL,
    `order_id` INT NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `rrn` VARCHAR(255) NOT NULL,
    `purpose` VARCHAR(255) NULL,
    `comment` VARCHAR(255) NULL,
    `coin_amount` INT NOT NULL,
    `merchant_id` VARCHAR(255) NOT NULL,
    `operation_id` VARCHAR(255) NOT NULL,
    `ecom_operation_id` VARCHAR(255) NOT NULL,
    `merchant_name` VARCHAR(255) NULL,
    `approval_code` VARCHAR(255) NULL,
    `status` VARCHAR(255) NOT NULL,
    `transaction_type` INT NOT NULL,
    `merchant_request_id` VARCHAR(255) NOT NULL,
    `transaction_currency` VARCHAR(255) NOT NULL,
    `merchant_commission` INT NULL,
    `creation_date_time` DATETIME NOT NULL,
    `modification_date_time` DATETIME NOT NULL,
    `action_code` VARCHAR(255) NULL,
    `response_code` VARCHAR(255) NULL,
    `description` VARCHAR(255) NULL,
    `processing_merchant_id` VARCHAR(255) NOT NULL,
    `processing_terminal_id` VARCHAR(255) NOT NULL,
    `transaction_response_info` LONGTEXT NULL,
    `payment_system` VARCHAR(255) NULL,
    `product_type` VARCHAR(255) NOT NULL,
    `notification_url` VARCHAR(255) NOT NULL,
    `payment_service_type` VARCHAR(255) NULL,
    `notification_encryption` VARCHAR(255) NOT NULL,
    `original_operation_id` VARCHAR(255) NOT NULL,
    `original_coin_amount` INT NOT NULL,
    `original_ecom_operation_id` VARCHAR(255) NOT NULL,
    `rrn_original` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`refund_id`),
    INDEX `idx_alliance_refund_order_id` (`order_id`),
    INDEX `idx_alliance_refund_merchant_req_id` (`merchant_request_id`),
    INDEX `idx_alliance_refund_merchant_id` (`merchant_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__virtuemart_payment_plg_alliance_auth_data` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    virtuemart_paymentmethod_id INT NOT NULL,
    device_id VARCHAR(255),
    refresh_token VARCHAR(255),
    auth_token VARCHAR(255),
    server_public LONGTEXT,
    token_expiration_date_time DATETIME,
    token_expiration DATETIME,
    session_expiration DATETIME,
    UNIQUE INDEX `idx_alliance_virtuemart_paymentmethod_id` (`virtuemart_paymentmethod_id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;